// Copy for the generalized per-event check-in flow — adapted from
// lib/wtetCheckinI18n.js's English strings, with event-specific bits
// (name, max passengers, contact) parameterized instead of hardcoded.
// The admin-authored waiver body text itself (checkin_waiver_text, one
// free-text column per event) stays whatever language the admin wrote it
// in — only the surrounding page copy is bilingual here.

export const CHECKIN_T = {
  en: {
    pageHeading: 'Event Check-in',
    pageHeadingSub: 'Trip details, waiver, and lunch — all in one place.',
    scrollCue: 'Scroll to begin',
    gateTitle: 'Confirm Your Email',
    gateBody: 'Enter the email you registered with to view and complete your check-in.',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    continueBtn: 'Continue',
    verifyingBtn: 'Verifying…',
    hiName: name => `Hi ${name}`,
    defaultTitle: 'Event Check-in',
    allDoneMsg: "You're all set — see you at the event.",
    incompleteMsg: 'Please complete the item(s) below marked outstanding before the event.',

    // Trip Details
    tripTitle: 'Trip Details',
    tripDoneLabel: 'Complete', tripPendingLabel: 'Not submitted',
    tripDoneMsg: 'Passengers, dietary needs, and WhatsApp number on file. Contact jerry@canvasroutes.com if anything\'s changed.',
    passengersHeader: 'Passengers — including driver',
    driverLabel: 'Driver',
    passengerLabel: n => `Passenger ${n}`,
    fullNameLabel: 'Full name *',
    ageLabel: 'Age *',
    removeBtn: 'Remove',
    addPassengerBtn: '+ Add passenger',
    passengersHint: 'Include everyone in the car — driver first, then any passengers.',
    maxPassengersNote: max => `Maximum ${max} people per car. Email jerry@canvasroutes.com if you need to bring more.`,
    passengerErrBoth: 'Name and age are required.',
    passengerErrName: 'Name is required.',
    passengerErrAge: 'Age is required.',
    dietaryLabel: 'Any dietary allergies or restrictions?',
    dietaryPlaceholder: 'e.g. nut allergy, vegetarian… or leave blank',
    whatsappLabel: 'WhatsApp number for group chat (optional)',
    whatsappPlaceholder: '+1 514 555 0100',
    whatsappHint: "We'll add you to the group chat for this event.",
    saveTripBtn: 'Save Trip Details',
    savingBtn: 'Saving…',

    // Waiver
    waiverTitle: 'Liability Waiver',
    frenchVersionNote: 'French version follows below',
    waiverDoneLabel: 'Signed', waiverPendingLabel: 'Not signed',
    signedByOn: 'Signed on',
    waiverLockedNote: 'This waiver is locked and cannot be edited. Contact jerry@canvasroutes.com for corrections.',
    agreeLabel: 'I have read and agree to the terms above.',
    signatureLabel: 'Signature — type your full legal name *',
    signaturePlaceholder: 'Type your full name',
    signatureHint: 'Typing your name here counts as your legal signature.',
    vehicleHeader: 'Vehicle',
    yearLabel: 'Year', makeLabel: 'Make', modelLabel: 'Model',
    bringingPassengers: "I'm bringing passenger(s)",
    bringingPassengersHint: 'This covers them under the same waiver — separate from the passengers you listed in Trip Details above, in case anyone changed.',
    passengerNamePlaceholder: 'Passenger name',
    agePlaceholder: 'Age',
    emergencyHeader: 'Emergency Contact',
    nameLabel: 'Name *', phoneLabel: 'Phone *',
    phonePlaceholder: '+1 514 000 0000',
    signWaiverBtn: 'Sign Waiver',
    signingBtn: 'Signing…',
    waiverErrAgree: 'You must check the box confirming you have read and agree to the waiver.',
    waiverErrName: 'Please type your full name as your signature.',
    waiverErrEmergency: 'Emergency contact name and phone are required.',

    // Lunch
    lunchTitle: 'Lunch Preference',
    lunchDoneLabel: 'Selected', lunchPendingLabel: 'Not selected', lunchDeadlinePassedLabel: 'Deadline passed',
    lunchSelectedPost: '.',
    lunchLockedNote: 'Selections are now locked. Contact jerry@canvasroutes.com if you need to make a change.',
    lunchChangeUntil: date => `You can change your selection until ${date}.`,
    changeSelectionBtn: 'Change selection',
    lunchDeadlinePassedBody: date => `The deadline to select a lunch dish (${date}) has passed. Contact`,
    lunchDeadlinePassedBody2: "if you haven't chosen yet.",
    chooseOneUntil: date => `Choose one for each person. You can change this until ${date}.`,
    saveSelectionBtn: 'Save Selection',
    cancelBtn: 'Cancel',
    lunchErrDish: 'Please select a dish for everyone in the car.',
    lunchNeedsTripFirst: 'Complete your trip details first so we know who\'s ordering lunch.',
    lunchForPerson: (name, isDriver) => `Lunch — ${name}${isDriver ? ' (Driver)' : ' (Passenger)'}`,
    lunchAllRequired: 'A dish selection is required for everyone in the car.',
    theMenu: 'The Menu',
    mainCourseHeader: 'Main Course Selection',

    genericError: 'Something went wrong.',
    networkError: 'Network error — please try again.',
    invalidEmailError: 'Please enter a valid email address.',
  },
  fr: {
    pageHeading: "Enregistrement à l'événement",
    pageHeadingSub: 'Détails du voyage, décharge et choix du repas — tout au même endroit.',
    scrollCue: 'Défiler pour commencer',
    gateTitle: 'Confirmez votre courriel',
    gateBody: "Entrez le courriel utilisé pour votre inscription afin de consulter et compléter votre enregistrement.",
    emailLabel: 'Courriel',
    emailPlaceholder: 'vous@exemple.com',
    continueBtn: 'Continuer',
    verifyingBtn: 'Vérification…',
    hiName: name => `Bonjour ${name}`,
    defaultTitle: "Enregistrement à l'événement",
    allDoneMsg: 'Tout est prêt — à bientôt sur la route.',
    incompleteMsg: 'Veuillez compléter les éléments ci-dessous marqués comme en attente avant l\'événement.',

    // Trip Details
    tripTitle: 'Détails du voyage',
    tripDoneLabel: 'Complété', tripPendingLabel: 'Non soumis',
    tripDoneMsg: "Passagers, restrictions alimentaires et numéro WhatsApp enregistrés. Contactez jerry@canvasroutes.com pour tout changement.",
    passengersHeader: 'Passagers — conducteur inclus',
    driverLabel: 'Conducteur',
    passengerLabel: n => `Passager ${n}`,
    fullNameLabel: 'Nom complet *',
    ageLabel: 'Âge *',
    removeBtn: 'Retirer',
    addPassengerBtn: '+ Ajouter un passager',
    passengersHint: 'Incluez tout le monde dans la voiture — le conducteur en premier, puis les passagers.',
    maxPassengersNote: max => `Maximum ${max} personnes par voiture. Écrivez à jerry@canvasroutes.com si vous devez en amener plus.`,
    passengerErrBoth: "Le nom et l'âge sont requis.",
    passengerErrName: 'Le nom est requis.',
    passengerErrAge: "L'âge est requis.",
    dietaryLabel: 'Allergies ou restrictions alimentaires?',
    dietaryPlaceholder: 'ex. allergie aux noix, végétarien… ou laissez vide',
    whatsappLabel: 'Numéro WhatsApp pour le groupe de discussion (optionnel)',
    whatsappPlaceholder: '+1 514 555 0100',
    whatsappHint: 'Nous vous ajouterons au groupe de discussion pour cet événement.',
    saveTripBtn: 'Enregistrer les détails',
    savingBtn: 'Enregistrement…',

    // Waiver
    waiverTitle: 'Décharge de responsabilité',
    frenchVersionNote: 'La version française suit ci-dessous',
    waiverDoneLabel: 'Signée', waiverPendingLabel: 'Non signée',
    signedByOn: 'Signée le',
    waiverLockedNote: 'Cette décharge est verrouillée et ne peut être modifiée. Contactez jerry@canvasroutes.com pour toute correction.',
    agreeLabel: "J'ai lu et j'accepte les conditions ci-dessus.",
    signatureLabel: 'Signature — inscrivez votre nom légal complet *',
    signaturePlaceholder: 'Inscrivez votre nom complet',
    signatureHint: 'Inscrire votre nom ici constitue votre signature légale.',
    vehicleHeader: 'Véhicule',
    yearLabel: 'Année', makeLabel: 'Marque', modelLabel: 'Modèle',
    bringingPassengers: "J'amène des passagers",
    bringingPassengersHint: "Ceci les couvre sous la même décharge — distinct des passagers indiqués dans Détails du voyage ci-dessus, en cas de changement.",
    passengerNamePlaceholder: 'Nom du passager',
    agePlaceholder: 'Âge',
    emergencyHeader: "Contact d'urgence",
    nameLabel: 'Nom *', phoneLabel: 'Téléphone *',
    phonePlaceholder: '+1 514 000 0000',
    signWaiverBtn: 'Signer la décharge',
    signingBtn: 'Signature…',
    waiverErrAgree: 'Vous devez cocher la case confirmant que vous avez lu et accepté la décharge.',
    waiverErrName: 'Veuillez inscrire votre nom complet comme signature.',
    waiverErrEmergency: "Le nom et le téléphone du contact d'urgence sont requis.",

    // Lunch
    lunchTitle: 'Choix du repas',
    lunchDoneLabel: 'Sélectionné', lunchPendingLabel: 'Non sélectionné', lunchDeadlinePassedLabel: 'Délai dépassé',
    lunchSelectedPost: '.',
    lunchLockedNote: 'Les sélections sont maintenant verrouillées. Contactez jerry@canvasroutes.com pour tout changement.',
    lunchChangeUntil: date => `Vous pouvez modifier votre sélection jusqu'au ${date}.`,
    changeSelectionBtn: 'Modifier la sélection',
    lunchDeadlinePassedBody: date => `La date limite pour choisir un plat (${date}) est passée. Contactez`,
    lunchDeadlinePassedBody2: "si vous n'avez pas encore choisi.",
    chooseOneUntil: date => `Choisissez un plat pour chaque personne. Vous pouvez modifier ceci jusqu'au ${date}.`,
    saveSelectionBtn: 'Enregistrer la sélection',
    cancelBtn: 'Annuler',
    lunchErrDish: 'Veuillez sélectionner un plat pour chaque personne dans la voiture.',
    lunchNeedsTripFirst: "Complétez d'abord les détails du voyage pour que nous sachions qui commande un repas.",
    lunchForPerson: (name, isDriver) => `Repas — ${name}${isDriver ? ' (Conducteur)' : ' (Passager)'}`,
    lunchAllRequired: 'Un choix de plat est requis pour chaque personne dans la voiture.',
    theMenu: 'Le Menu',
    mainCourseHeader: 'Choix du plat principal',

    genericError: "Une erreur s'est produite.",
    networkError: 'Erreur réseau — veuillez réessayer.',
    invalidEmailError: 'Veuillez entrer une adresse courriel valide.',
  },
}

export function checkinDateLocale(lang) { return lang === 'fr' ? 'fr-CA' : 'en-CA' }
