// Canvas Routes — Car Spec Sheets
// Event: Grand Prix Weekend · Cars, Coffee & Cruise · May 23, 2026
// URL: /spec/[owner]/[car]

const CARS = [
  // ── May 23 ──────────────────────────────────────────────────────────────────
  {
    owner: 'cedric',
    car: '1997-bmw-e36-convertible',
    displayName: 'Cedric',
    year: '1997',
    make: 'BMW',
    model: 'E36 328i Convertible',
    specs: [
      { label: 'Engine',      value: '2.8L Inline-6 (M52)' },
      { label: 'Horsepower',  value: '190 hp' },
      { label: '0–60 mph',    value: '7.3 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
  },
  {
    owner: 'jeanfrederic',
    car: '2025-maserati-granturismo-trofeo',
    displayName: 'Jean Frederic',
    year: '2025',
    make: 'Maserati',
    model: 'GranTurismo Trofeo',
    specs: [
      { label: 'Engine',      value: '3.0L Twin-Turbo V6 (Nettuno)' },
      { label: 'Horsepower',  value: '542 hp' },
      { label: 'Torque',      value: '479 lb-ft' },
      { label: 'Transmission', value: '8-Speed Automatic' },
      { label: '0–60 mph',    value: '3.5 sec (stock)' },
      { label: 'Drivetrain',  value: 'AWD' },
    ],
  },
  {
    owner: 'sacha',
    car: '2010-honda-civic',
    displayName: 'Sacha',
    year: '2010',
    make: 'Honda',
    model: 'Civic',
    specs: [
      { label: 'Engine',      value: '1.8L Inline-4 (R18A1)' },
      { label: 'Horsepower',  value: '140 hp' },
      { label: 'Torque',      value: '128 lb-ft' },
      { label: '0–60 mph',    value: '8.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'FWD' },
    ],
    mods: 'Aftermarket front bumper · Front lip · Side skirts · Rear diffuser · Coilovers (lowered) · Chrome wheels · New paint job',
  },

  // ── May 21 ──────────────────────────────────────────────────────────────────
  {
    owner: 'anthony',
    car: '2019-bmw-m5-competition',
    displayName: 'Anthony',
    year: '2019',
    make: 'BMW',
    model: 'M5 Competition',
    color: 'Matte Black',
    specs: [
      { label: 'Engine',      value: '4.4L Twin-Turbo V8' },
      { label: 'Horsepower',  value: '800 hp' },
      { label: '0–60 mph',    value: '3.1 sec (stock)' },
      { label: 'Drivetrain',  value: 'AWD (xDrive)' },
    ],
    mods: 'Stage 2 tune · Catless downpipes',
  },

  // ── May 20 ──────────────────────────────────────────────────────────────────
  {
    owner: 'adam',
    car: '2021-bmw-228i-gran-coupe',
    displayName: 'Adam',
    year: '2021',
    make: 'BMW',
    model: '228i Gran Coupé',
    specs: [
      { label: 'Engine',      value: '2.0L Turbocharged Inline-4' },
      { label: 'Horsepower',  value: '228 hp' },
      { label: '0–60 mph',    value: '6.6 sec (stock)' },
      { label: 'Drivetrain',  value: 'FWD' },
    ],
    note: 'Tuned',
  },
  {
    owner: 'michel',
    car: '2025-lotus-emira',
    displayName: 'Michel',
    year: '2025',
    make: 'Lotus',
    model: 'Emira',
    color: 'Vivid Red',
    specs: [
      { label: 'Engine',      value: '3.5L Supercharged V6' },
      { label: 'Horsepower',  value: '400 hp' },
      { label: '0–60 mph',    value: '4.3 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
  },
  {
    owner: 'jafar',
    car: '1990-bmw-325i',
    displayName: 'Jafar',
    year: '1990',
    make: 'BMW',
    model: '325i (E30)',
    specs: [
      { label: 'Engine',      value: '2.5L Inline-6 (M20B25)' },
      { label: 'Horsepower',  value: '168 hp' },
      { label: '0–60 mph',    value: '8.8 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
  },
  {
    owner: 'dany',
    car: '2002-porsche-911-carrera-4s',
    displayName: 'Dany',
    year: '2002',
    make: 'Porsche',
    model: '911 Carrera 4S (996)',
    color: 'Phoenix Yellow — Paint to Sample (Code 99)',
    specs: [
      { label: 'Engine',      value: '3.6L Flat-Six (M96/03)' },
      { label: 'Horsepower',  value: '320 hp' },
      { label: 'Transmission', value: 'Tiptronic S' },
      { label: '0–60 mph',    value: '5.1 sec (stock)' },
      { label: 'Drivetrain',  value: 'AWD' },
    ],
    note: 'One of two ever produced in Phoenix Yellow — a Porsche Paint to Sample colour. Accompanied by a Certificate of Authenticity signed by the President of Porsche Cars North America.',
    mods: 'Advanced Technic Package (Bi-Xenon, Bose, headlight washers) · Parking assist · Self-dimming mirrors · Heated front seats · Wheel caps with coloured crest',
  },

  // ── May 19 ──────────────────────────────────────────────────────────────────
  {
    owner: 'aicha',
    car: '1972-mercedes-450-sl',
    displayName: 'Aicha',
    year: '1972',
    make: 'Mercedes-Benz',
    model: '450 SL (R107)',
    color: 'White',
    specs: [
      { label: 'Engine',      value: '4.5L V8 (M117)' },
      { label: 'Horsepower',  value: '190 hp' },
      { label: 'Transmission', value: 'Automatic' },
      { label: '0–60 mph',    value: '9.3 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'Fully original and well-maintained. White exterior with midnight blue leather interior — a stunning combination in remarkable condition for her age.',
    mods: 'Dual top: navy blue soft top + removable hardtop · Chrome bumpers · Original alloy wheels · Midnight blue leather interior',
  },
  {
    owner: 'ahmed',
    car: '2001-jaguar-xj8',
    displayName: 'Ahmed',
    year: '2001',
    make: 'Jaguar',
    model: 'XJ8',
    specs: [
      { label: 'Engine',      value: '4.0L V8 (AJ-V8)' },
      { label: 'Horsepower',  value: '290 hp' },
      { label: 'Torque',      value: '290 lb-ft' },
      { label: 'Transmission', value: '5-Speed Automatic' },
      { label: '0–60 mph',    value: '6.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    mods: 'Aftermarket wheels',
  },
  {
    owner: 'john',
    car: '1985-ford-mustang-gt',
    displayName: 'John',
    year: '1985',
    make: 'Ford',
    model: 'Mustang GT',
    specs: [
      { label: 'Engine',      value: '5.0L V8 (302 HO)' },
      { label: 'Horsepower',  value: '210 hp' },
      { label: '0–60 mph',    value: '6.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
  },
  {
    owner: 'alec',
    car: '1995-mazda-miata-m-edition',
    displayName: 'Alec',
    year: '1995',
    make: 'Mazda',
    model: 'MX-5 Miata M Edition',
    color: 'Merlot Mica',
    specs: [
      { label: 'Engine',      value: '1.8L Inline-4 (BP)' },
      { label: 'Horsepower',  value: '128 hp @ 6,500 rpm' },
      { label: '0–60 mph',    value: '8.7 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    mods: 'Style bar · Aftermarket wheels (seeking original BBS basket weave)',
  },
  {
    owner: 'darnell',
    car: '2024-porsche-718-cayman-gts-40',
    displayName: 'Darnell',
    year: '2024',
    make: 'Porsche',
    model: '718 Cayman GTS 4.0',
    specs: [
      { label: 'Engine',      value: '4.0L Naturally Aspirated Flat-Six' },
      { label: 'Horsepower',  value: '394 hp' },
      { label: '0–60 mph',    value: '4.3 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
  },

  // ── May 18 ──────────────────────────────────────────────────────────────────
  {
    owner: 'maxime',
    car: '1991-lotus-elan-m100',
    displayName: 'Maxime',
    year: '1991',
    make: 'Lotus',
    model: 'Elan M100 (USA Spec)',
    color: 'Calypso Red (Code A23)',
    specs: [
      { label: 'Engine',      value: '1.6L Turbocharged Inline-4 (4XE1-MT)' },
      { label: 'Horsepower',  value: '162 hp stock / up to 215 hp (Mountain Chip)' },
      { label: 'Transmission', value: '5-Speed Manual' },
      { label: '0–60 mph',    value: '6.5 sec (stock)' },
      { label: 'Drivetrain',  value: 'FWD' },
    ],
    note: '397th of 538 USA-spec Elans built. Accompanied by a Certificate of Authenticity and original factory build letter.',
    mods: 'Mountain Chip Switcher V5 (4 boost profiles: 165–215 hp) · PECO T304 stainless exhaust · HiSpec 283mm 4-piston front brakes · LED headlamps',
  },

  // ── May 17 ──────────────────────────────────────────────────────────────────
  {
    owner: 'tanya',
    car: '2012-porsche-cayman-s-black-edition',
    displayName: 'Tanya',
    year: '2012',
    make: 'Porsche',
    model: 'Cayman S Black Edition',
    specs: [
      { label: 'Engine',      value: '3.4L Flat-Six' },
      { label: 'Horsepower',  value: '330 hp' },
      { label: '0–60 mph',    value: '5.0 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: '71 of 500 — Limited to 500 units worldwide',
  },
  {
    owner: 'mohamad',
    car: '2018-bmw-m4',
    displayName: 'Mohamad',
    year: '2018',
    make: 'BMW',
    model: 'M4',
    specs: [
      { label: 'Engine',      value: '3.0L Twin-Turbo Inline-6 (S55)' },
      { label: 'Horsepower',  value: '425 hp' },
      { label: '0–60 mph',    value: '4.4 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
  },
  {
    owner: 'aayush',
    car: '2019-alfa-romeo-giulia-q4',
    displayName: 'Aayush',
    year: '2019',
    make: 'Alfa Romeo',
    model: 'Giulia Ti Q4 — Nero Edizione',
    color: 'Rossi Red',
    specs: [
      { label: 'Engine',      value: '2.0L Turbocharged Inline-4' },
      { label: 'Horsepower',  value: '300 hp' },
      { label: '0–60 mph',    value: '5.1 sec (stock)' },
      { label: 'Drivetrain',  value: 'AWD (Q4)' },
    ],
    mods: 'Quadrifoglio-style spoiler · Aftermarket diffuser · AFE axle-back exhausts · Full PPF with ceramic coating',
  },
  {
    owner: 'shadi',
    car: '2023-chevrolet-corvette',
    displayName: 'Shadi',
    year: '2023',
    make: 'Chevrolet',
    model: 'Corvette C8 Z51 — 70th Anniversary Edition',
    color: 'Custom Tiffany Blue PPF (Bespoke Wraps)',
    specs: [
      { label: 'Engine',      value: '6.2L Naturally Aspirated V8 (LT2)' },
      { label: 'Horsepower',  value: '490 hp' },
      { label: 'Transmission', value: '8-Speed Dual Clutch' },
      { label: '0–60 mph',    value: '2.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD (mid-engine)' },
    ],
    mods: 'Custom valved exhaust · Custom Tiffany-inspired PPF wrap (Bespoke Wraps)',
  },

  // ── May 16 ──────────────────────────────────────────────────────────────────
  {
    owner: 'fortunato',
    car: '2018-alfa-romeo-giulia-quadrifoglio',
    displayName: 'Fortunato',
    year: '2018',
    make: 'Alfa Romeo',
    model: 'Giulia Quadrifoglio',
    specs: [
      { label: 'Engine',      value: '2.9L Twin-Turbo V6' },
      { label: 'Horsepower',  value: '505 hp' },
      { label: '0–60 mph',    value: '3.8 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
  },
  {
    owner: 'nicolas',
    car: '2024-bmw-m2',
    displayName: 'Nicolás',
    year: '2024',
    make: 'BMW',
    model: 'M2 (G87)',
    color: 'Jet Black',
    specs: [
      { label: 'Engine',      value: '3.0L Twin-Turbo Inline-6 (S58B30T0)' },
      { label: 'Horsepower',  value: '453 hp' },
      { label: 'Torque',      value: '406 lb-ft' },
      { label: 'Transmission', value: '6-Speed Manual (ZF-GS6)' },
      { label: '0–60 mph',    value: '3.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    mods: 'Full body PPF · MAD air intakes · Eibach lowering springs · Apex VS5 wheels (floating BMW logos) · Michelin Pilot Sport 4S 285/35/19 all around',
  },
  {
    owner: 'jocelyn',
    car: '1966-lotus-elan',
    displayName: 'Jocelyn',
    year: '1966',
    make: 'Lotus',
    model: 'Elan S3 Coupé',
    color: 'Lotus Yellow',
    specs: [
      { label: 'Engine',      value: '1.6L Twin-Cam Inline-4 (Lotus-Ford)' },
      { label: 'Horsepower',  value: '105 hp' },
      { label: '0–60 mph',    value: '7.1 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    mods: 'Former race car · Modified suspension · Original engine & transmission retained · Various non-original details throughout',
  },
  {
    owner: 'marko',
    car: '1969-mg-mgb',
    displayName: 'Marko',
    year: '1969',
    make: 'MG',
    model: 'MGB',
    specs: [
      { label: 'Engine',      value: '1.8L Inline-4 (B-Series)' },
      { label: 'Horsepower',  value: '95 hp' },
      { label: '0–60 mph',    value: '11.5 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
  },

  // ── May 15 ──────────────────────────────────────────────────────────────────
  {
    owner: 'yvon',
    car: '2014-porsche-911-turbo-s',
    displayName: 'Yvon',
    year: '2014',
    make: 'Porsche',
    model: '911 Turbo S Cabriolet',
    color: 'Basalt Black Metallic',
    specs: [
      { label: 'Engine',      value: '3.8L Twin-Turbo Flat-Six (991.1)' },
      { label: 'Horsepower',  value: '560 hp @ 6,500–6,750 rpm' },
      { label: 'Torque',      value: '516 lb-ft (553 lb-ft w/ Overboost)' },
      { label: 'Transmission', value: '7-Speed PDK' },
      { label: 'Top Speed',   value: '197 mph (318 km/h)' },
      { label: '0–60 mph',    value: '2.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'AWD' },
    ],
    mods: 'PCCB ceramic brakes (yellow calipers) · PDCC active anti-roll · Rear-axle steering · Active aero (front spoiler + variable rear wing) · 20" forged wheels with central locking',
  },
  {
    owner: 'daniel',
    car: '2025-porsche-cayman-gts-40',
    displayName: 'Daniel',
    year: '2025',
    make: 'Porsche',
    model: '718 Cayman GTS 4.0',
    color: 'Chalk',
    specs: [
      { label: 'Engine',      value: '4.0L Naturally Aspirated Flat-Six' },
      { label: 'Horsepower',  value: '394 hp' },
      { label: 'Transmission', value: '6-Speed Manual' },
      { label: '0–60 mph',    value: '3.8 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    mods: 'PCCB ceramic brakes (factory option)',
  },

  // ── May 14 ──────────────────────────────────────────────────────────────────
  {
    owner: 'luc',
    car: '2018-cadillac-escalade-platinum',
    displayName: 'Luc',
    year: '2018',
    make: 'Cadillac',
    model: 'Escalade Platinum',
    specs: [
      { label: 'Engine',      value: '6.2L Naturally Aspirated V8' },
      { label: 'Horsepower',  value: '420 hp' },
      { label: '0–60 mph',    value: '6.1 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD (4WD available)' },
    ],
  },
  {
    owner: 'luc',
    car: '1975-chevrolet-caprice-classic',
    displayName: 'Luc',
    year: '1975',
    make: 'Chevrolet',
    model: 'Caprice Classic',
    specs: [
      { label: 'Engine',      value: '5.7L V8 (350 cu in)' },
      { label: 'Horsepower',  value: '145 hp' },
      { label: '0–60 mph',    value: '~13 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
  },
  {
    owner: 'xavier',
    car: '2003-porsche-boxster-s',
    displayName: 'Xavier',
    year: '2003',
    make: 'Porsche',
    model: 'Boxster S',
    color: 'Silver',
    specs: [
      { label: 'Engine',      value: '3.2L Flat-Six (Mid-Engine)' },
      { label: 'Horsepower',  value: '258 hp' },
      { label: '0–60 mph',    value: '5.5 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    mods: 'M030 Sport Chassis Package',
  },
  {
    owner: 'jeanphilippe',
    car: '2011-bmw-135i',
    displayName: 'Jean-Philippe',
    year: '2011',
    make: 'BMW',
    model: '135i',
    specs: [
      { label: 'Engine',      value: '3.0L Twin-Turbo Inline-6 (N55)' },
      { label: 'Horsepower',  value: '300 hp' },
      { label: '0–60 mph',    value: '5.0 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
  },
  {
    owner: 'julien',
    car: '2005-porsche-911-carrera-s',
    displayName: 'Julien',
    year: '2005',
    make: 'Porsche',
    model: '911 Carrera S Cabriolet',
    specs: [
      { label: 'Engine',      value: '3.8L Flat-Six' },
      { label: 'Horsepower',  value: '355 hp' },
      { label: '0–60 mph',    value: '4.8 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
  },
  {
    owner: 'normand',
    car: 'chevrolet-corvette-c8',
    displayName: 'Normand',
    year: '2020',
    make: 'Chevrolet',
    model: 'Corvette Stingray C8',
    specs: [
      { label: 'Engine',      value: '6.2L Naturally Aspirated V8 (LT2)' },
      { label: 'Horsepower',  value: '490 hp' },
      { label: '0–60 mph',    value: '2.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD (mid-engine)' },
    ],
  },
  {
    owner: 'paul',
    car: '2013-porsche-boxster',
    displayName: 'Paul',
    year: '2013',
    make: 'Porsche',
    model: 'Boxster',
    specs: [
      { label: 'Engine',      value: '2.7L Flat-Six (Mid-Engine)' },
      { label: 'Horsepower',  value: '265 hp' },
      { label: '0–60 mph',    value: '5.5 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
  },
  {
    owner: 'thaira',
    car: '1997-bmw-z3',
    displayName: 'Thaira',
    year: '1997',
    make: 'BMW',
    model: 'Z3',
    specs: [
      { label: 'Engine',      value: '1.9L Inline-4 (M44)' },
      { label: 'Horsepower',  value: '138 hp' },
      { label: '0–60 mph',    value: '8.6 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
  },
  {
    owner: 'yves',
    car: '2021-porsche-911-carrera-4',
    displayName: 'Yves',
    year: '2021',
    make: 'Porsche',
    model: '911 Carrera 4',
    specs: [
      { label: 'Engine',      value: '3.0L Twin-Turbo Flat-Six' },
      { label: 'Horsepower',  value: '379 hp' },
      { label: '0–60 mph',    value: '4.0 sec (stock)' },
      { label: 'Drivetrain',  value: 'AWD' },
    ],
  },
  {
    owner: 'domenic',
    car: '2008-corvette-z06',
    displayName: 'Domenic',
    year: '2008',
    make: 'Chevrolet',
    model: 'Corvette Z06',
    color: 'Velocity Yellow',
    specs: [
      { label: 'Engine',      value: '7.0L Naturally Aspirated V8 (LS7)' },
      { label: 'Horsepower',  value: '550 whp' },
      { label: '0–60 mph',    value: '3.7 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    mods: 'Milled/ported heads · Kooks 2" headers · Kooks catless X-pipe · Custom mufflers',
  },
]

export function getCar(owner, car) {
  return CARS.find(c => c.owner === owner && c.car === car) || null
}

export default CARS
