// Canvas Routes — Car Spec Sheets
// Event: Grand Prix Weekend · Cars, Coffee & Cruise · May 23, 2026
// URL: /spec/[owner]/[car]

const CARS = [
  // ── May 23 ──────────────────────────────────────────────────────────────────
  {
    owner: 'jonathan',
    car: '2024-lotus-emira-v6',
    displayName: 'Jonathan',
    year: '2024',
    make: 'Lotus',
    model: 'Emira V6',
    specs: [
      { label: 'Engine',      value: '3.5L Supercharged V6' },
      { label: 'Horsepower',  value: '400 hp' },
      { label: '0–60 mph',    value: '4.3 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'The last petrol Lotus ever built — and arguably the most complete one. The Emira V6 is Hethel\'s farewell letter, written at full throttle.',
  },
  {
    owner: 'omar',
    car: '2009-bmw-e92-335xi',
    displayName: 'Omar',
    year: '2009',
    make: 'BMW',
    model: 'E92 335xi',
    specs: [
      { label: 'Engine',      value: '3.0L Twin-Turbo Inline-6 (N54)' },
      { label: 'Horsepower',  value: '300 hp (stock)' },
      { label: '0–60 mph',    value: '5.3 sec (stock)' },
      { label: 'Drivetrain',  value: 'AWD (xDrive)' },
    ],
    note: 'The N54\'s twin turbos were practically begging to be tuned. Stage 2+ transforms what BMW left on the table into something the factory engineers only dreamed about.',
    mods: 'Stage 2+ tune',
  },
  {
    owner: 'cedric',
    car: '1997-bmw-e36-convertible',
    displayName: 'Cedric',
    year: '1997',
    make: 'BMW',
    model: 'E36 328i Convertible',
    specs: [
      { label: 'Engine',      value: '2.8L Inline-6 (M52)' },
      { label: 'Horsepower',  value: '190 hp' },
      { label: '0–60 mph',    value: '7.3 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'Open-top, straight-six, rear-wheel drive. The E36 convertible is the BMW formula at its most honest — and most enjoyable.',
  },
  {
    owner: 'jeanfrederic',
    car: '2025-maserati-granturismo-trofeo',
    displayName: 'Jean Frederic',
    year: '2025',
    make: 'Maserati',
    model: 'GranTurismo Trofeo',
    specs: [
      { label: 'Engine',      value: '3.0L Twin-Turbo V6 (Nettuno)' },
      { label: 'Horsepower',  value: '542 hp' },
      { label: 'Torque',      value: '479 lb-ft' },
      { label: 'Transmission', value: '8-Speed Automatic' },
      { label: '0–60 mph',    value: '3.5 sec (stock)' },
      { label: 'Drivetrain',  value: 'AWD' },
    ],
    note: 'The Nettuno V6 was born in Formula 1 — pre-chamber combustion technology straight from Ferrari\'s racing programme, housed in a grand tourer built for the open road.',
  },
  {
    owner: 'sacha',
    car: '2010-honda-civic',
    displayName: 'Sacha',
    year: '2010',
    make: 'Honda',
    model: 'Civic',
    specs: [
      { label: 'Engine',      value: '1.8L Inline-4 (R18A1)' },
      { label: 'Horsepower',  value: '140 hp' },
      { label: 'Torque',      value: '128 lb-ft' },
      { label: '0–60 mph',    value: '8.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'FWD' },
    ],
    note: 'Every great build starts somewhere. This Civic is proof that passion and vision matter more than the badge on the hood.',
    mods: 'Aftermarket front bumper · Front lip · Side skirts · Rear diffuser · Coilovers (lowered) · Chrome wheels · New paint job',
  },

  // ── May 21 ──────────────────────────────────────────────────────────────────
  {
    owner: 'anthony',
    car: '2019-bmw-m5-competition',
    displayName: 'Anthony',
    year: '2019',
    make: 'BMW',
    model: 'M5 Competition',
    color: 'Matte Black',
    specs: [
      { label: 'Engine',      value: '4.4L Twin-Turbo V8' },
      { label: 'Horsepower',  value: '800 hp' },
      { label: '0–60 mph',    value: '3.1 sec (stock)' },
      { label: 'Drivetrain',  value: 'AWD (xDrive)' },
    ],
    note: '800 horsepower wrapped in matte black — a wolf that doesn\'t bother with sheep\'s clothing.',
    mods: 'Stage 2 tune · Catless downpipes',
  },

  // ── May 20 ──────────────────────────────────────────────────────────────────
  {
    owner: 'adam',
    car: '2021-bmw-228i-gran-coupe',
    displayName: 'Adam',
    year: '2021',
    make: 'BMW',
    model: '228i Gran Coupé',
    specs: [
      { label: 'Engine',      value: '2.0L Turbocharged Inline-4' },
      { label: 'Horsepower',  value: '228 hp' },
      { label: '0–60 mph',    value: '6.6 sec (stock)' },
      { label: 'Drivetrain',  value: 'FWD' },
    ],
    note: 'The 2 Series Gran Coupé doesn\'t announce itself. It just shows up faster than expected — tuned and ready to prove a point.',
    mods: 'Tune',
  },
  {
    owner: 'michel',
    car: '2025-lotus-emira',
    displayName: 'Michel',
    year: '2025',
    make: 'Lotus',
    model: 'Emira',
    color: 'Vivid Red',
    specs: [
      { label: 'Engine',      value: '3.5L Supercharged V6' },
      { label: 'Horsepower',  value: '400 hp' },
      { label: '0–60 mph',    value: '4.3 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'Vivid Red and supercharged — the Emira V6 doesn\'t ask for attention. It commands it.',
  },
  {
    owner: 'jafar',
    car: '1990-bmw-325i',
    displayName: 'Jafar',
    year: '1990',
    make: 'BMW',
    model: '325i (E30)',
    specs: [
      { label: 'Engine',      value: '2.5L Inline-6 (M20B25)' },
      { label: 'Horsepower',  value: '168 hp' },
      { label: '0–60 mph',    value: '8.8 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'The E30 is the BMW that defined the breed. Decades on, drivers still seek one out specifically because nothing else feels quite like it.',
  },
  {
    owner: 'dany',
    car: '2002-porsche-911-carrera-4s',
    displayName: 'Dany',
    year: '2002',
    make: 'Porsche',
    model: '911 Carrera 4S (996)',
    color: 'Phoenix Yellow — Paint to Sample (Code 99)',
    specs: [
      { label: 'Engine',      value: '3.6L Flat-Six (M96/03)' },
      { label: 'Horsepower',  value: '320 hp' },
      { label: 'Transmission', value: 'Tiptronic S' },
      { label: '0–60 mph',    value: '5.1 sec (stock)' },
      { label: 'Drivetrain',  value: 'AWD' },
    ],
    note: 'One of two ever produced in Phoenix Yellow — a Porsche Paint to Sample colour. Accompanied by a Certificate of Authenticity signed by the President of Porsche Cars North America.',
    mods: 'Advanced Technic Package (Bi-Xenon, Bose, headlight washers) · Parking assist · Self-dimming mirrors · Heated front seats · Wheel caps with coloured crest',
  },

  // ── May 19 ──────────────────────────────────────────────────────────────────
  {
    owner: 'aicha',
    car: '1972-mercedes-450-sl',
    displayName: 'Aicha',
    year: '1972',
    make: 'Mercedes-Benz',
    model: '450 SL (R107)',
    color: 'White',
    specs: [
      { label: 'Engine',      value: '4.5L V8 (M117)' },
      { label: 'Horsepower',  value: '190 hp' },
      { label: 'Transmission', value: 'Automatic' },
      { label: '0–60 mph',    value: '9.3 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'Fully original and well-maintained. White exterior with midnight blue leather interior — a stunning combination in remarkable condition for her age.',
    mods: 'Dual top: navy blue soft top + removable hardtop · Chrome bumpers · Original alloy wheels · Midnight blue leather interior',
  },
  {
    owner: 'ahmed',
    car: '2001-jaguar-xj8',
    displayName: 'Ahmed',
    year: '2001',
    make: 'Jaguar',
    model: 'XJ8',
    specs: [
      { label: 'Engine',      value: '4.0L V8 (AJ-V8)' },
      { label: 'Horsepower',  value: '290 hp' },
      { label: 'Torque',      value: '290 lb-ft' },
      { label: 'Transmission', value: '5-Speed Automatic' },
      { label: '0–60 mph',    value: '6.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'British luxury with V8 presence. The XJ8 carries itself with a quiet confidence that only comes with age — and history.',
    mods: 'Aftermarket wheels',
  },
  {
    owner: 'john',
    car: '1985-ford-mustang-gt',
    displayName: 'John',
    year: '1985',
    make: 'Ford',
    model: 'Mustang GT',
    specs: [
      { label: 'Engine',      value: '5.0L V8 (302 HO)' },
      { label: 'Horsepower',  value: '210 hp' },
      { label: '0–60 mph',    value: '6.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'The Fox body defined a generation of American muscle. Raw, loud, and unapologetically itself — exactly as it should be.',
  },
  {
    owner: 'alec',
    car: '1995-mazda-miata-m-edition',
    displayName: 'Alec',
    year: '1995',
    make: 'Mazda',
    model: 'MX-5 Miata M Edition',
    color: 'Merlot Mica',
    specs: [
      { label: 'Engine',      value: '1.8L Inline-4 (BP)' },
      { label: 'Horsepower',  value: '128 hp @ 6,500 rpm' },
      { label: '0–60 mph',    value: '8.7 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
      { label: 'Production',  value: '1 of 3,500 — M Edition (1995 only)' },
    ],
    note: 'Merlot Mica was exclusive to the 1995 M Edition, the final year of the NA generation. Just 3,500 were built.',
    mods: 'Style bar · Aftermarket wheels (seeking original BBS basket weave)',
  },
  {
    owner: 'darnell',
    car: '2024-porsche-718-cayman-gts-40',
    displayName: 'Darnell',
    year: '2024',
    make: 'Porsche',
    model: '718 Cayman GTS 4.0',
    specs: [
      { label: 'Engine',      value: '4.0L Naturally Aspirated Flat-Six' },
      { label: 'Horsepower',  value: '394 hp' },
      { label: '0–60 mph',    value: '4.3 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'Porsche\'s purest sports car. The GTS 4.0 exists to remind you that mid-engine balance and a naturally aspirated flat-six are all you really need.',
  },

  // ── May 18 ──────────────────────────────────────────────────────────────────
  {
    owner: 'maxime',
    car: '1991-lotus-elan-m100',
    displayName: 'Maxime',
    year: '1991',
    make: 'Lotus',
    model: 'Elan M100 (USA Spec)',
    color: 'Calypso Red (Code A23)',
    specs: [
      { label: 'Engine',      value: '1.6L Turbocharged Inline-4 (4XE1-MT)' },
      { label: 'Horsepower',  value: '162 hp stock / up to 215 hp (Mountain Chip)' },
      { label: 'Transmission', value: '5-Speed Manual' },
      { label: '0–60 mph',    value: '6.5 sec (stock)' },
      { label: 'Drivetrain',  value: 'FWD' },
    ],
    note: '397th of 538 USA-spec Elans built. Accompanied by a Certificate of Authenticity and original factory build letter.',
    mods: 'Mountain Chip Switcher V5 (4 boost profiles: 165–215 hp) · PECO T304 stainless exhaust · HiSpec 283mm 4-piston front brakes · LED headlamps',
  },

  // ── May 17 ──────────────────────────────────────────────────────────────────
  {
    owner: 'tanya',
    car: '2012-porsche-cayman-s-black-edition',
    displayName: 'Tanya',
    year: '2012',
    make: 'Porsche',
    model: 'Cayman S Black Edition',
    specs: [
      { label: 'Engine',      value: '3.4L Flat-Six' },
      { label: 'Horsepower',  value: '330 hp' },
      { label: '0–60 mph',    value: '5.0 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: '71 of 500 produced worldwide. The Black Edition arrived blacked-out and limited — and remains one of the most collectible Caymans Porsche ever built.',
  },
  {
    owner: 'mohamad',
    car: '2018-bmw-m4',
    displayName: 'Mohamad',
    year: '2018',
    make: 'BMW',
    model: 'M4 Competition (F82)',
    color: 'Black Sapphire Metallic',
    specs: [
      { label: 'Engine',      value: '3.0L Twin-Turbo Inline-6 (S55)' },
      { label: 'Horsepower',  value: '444 hp' },
      { label: '0–60 mph',    value: '4.1 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'The S55 Competition rewrote what a turbocharged M engine could sound like. Black Sapphire makes it look as serious as it performs.',
    mods: 'M Performance exhaust · Silverstone Extended Merino leather interior',
  },
  {
    owner: 'aayush',
    car: '2019-alfa-romeo-giulia-q4',
    displayName: 'Aayush',
    year: '2019',
    make: 'Alfa Romeo',
    model: 'Giulia Ti Q4 — Nero Edizione',
    color: 'Rossi Red',
    specs: [
      { label: 'Engine',      value: '2.0L Turbocharged Inline-4' },
      { label: 'Horsepower',  value: '300 hp' },
      { label: '0–60 mph',    value: '5.1 sec (stock)' },
      { label: 'Drivetrain',  value: 'AWD (Q4)' },
    ],
    note: 'Rossi Red, Nero Edizione, Quadrifoglio-style spoiler. Aayush didn\'t just buy a Giulia — he built the version Alfa Romeo forgot to make.',
    mods: 'Quadrifoglio-style spoiler · Aftermarket diffuser · AFE axle-back exhausts · Full PPF with ceramic coating',
  },
  {
    owner: 'shadi',
    car: '2023-chevrolet-corvette',
    displayName: 'Shadi',
    year: '2023',
    make: 'Chevrolet',
    model: 'Corvette C8 Z51 — 70th Anniversary Edition',
    color: 'Custom Tiffany Blue PPF (Bespoke Wraps)',
    specs: [
      { label: 'Engine',      value: '6.2L Naturally Aspirated V8 (LT2)' },
      { label: 'Horsepower',  value: '490 hp' },
      { label: 'Transmission', value: '8-Speed Dual Clutch' },
      { label: '0–60 mph',    value: '2.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD (mid-engine)' },
    ],
    note: 'A custom Tiffany-inspired PPF wrap on a 70th Anniversary Z51 — this Corvette is as much art as it is automobile.',
    mods: 'Custom valved exhaust · Custom Tiffany-inspired PPF wrap (Bespoke Wraps)',
  },

  // ── May 16 ──────────────────────────────────────────────────────────────────
  {
    owner: 'fortunato',
    car: '2018-alfa-romeo-giulia-quadrifoglio',
    displayName: 'Fortunato',
    year: '2018',
    make: 'Alfa Romeo',
    model: 'Giulia Quadrifoglio',
    specs: [
      { label: 'Engine',      value: '2.9L Twin-Turbo V6' },
      { label: 'Horsepower',  value: '505 hp' },
      { label: '0–60 mph',    value: '3.8 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'When it debuted, the Giulia Quadrifoglio set the Nürburgring record for production sedans. Ferrari\'s hand is evident in every rev of the twin-turbo V6.',
  },
  {
    owner: 'nicolas',
    car: '2024-bmw-m2',
    displayName: 'Nicolás',
    year: '2024',
    make: 'BMW',
    model: 'M2 (G87)',
    color: 'Jet Black',
    specs: [
      { label: 'Engine',      value: '3.0L Twin-Turbo Inline-6 (S58B30T0)' },
      { label: 'Horsepower',  value: '453 hp' },
      { label: 'Torque',      value: '406 lb-ft' },
      { label: 'Transmission', value: '6-Speed Manual (ZF-GS6)' },
      { label: '0–60 mph',    value: '3.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'One of the last small BMW M cars with a manual gearbox. Jet black, lowered, and built the way it always should have been.',
    mods: 'Full body PPF · MAD air intakes · Eibach lowering springs · Apex VS5 wheels (floating BMW logos) · Michelin Pilot Sport 4S 285/35/19 all around',
  },
  {
    owner: 'jocelyn',
    car: '1966-lotus-elan',
    displayName: 'Jocelyn',
    year: '1966',
    make: 'Lotus',
    model: 'Elan S3 Coupé',
    color: 'Lotus Yellow',
    specs: [
      { label: 'Engine',      value: '1.6L Twin-Cam Inline-4 (Lotus-Ford)' },
      { label: 'Horsepower',  value: '105 hp' },
      { label: '0–60 mph',    value: '7.1 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'A former race car wearing Lotus Yellow — the colour Chapman chose for competition. The Elan S3 remains one of the most perfectly proportioned sports cars ever designed.',
    mods: 'Former race car · Modified suspension · Original engine & transmission retained · Various non-original details throughout',
  },
  {
    owner: 'marko',
    car: '1969-mg-mgb',
    displayName: 'Marko',
    year: '1969',
    make: 'MG',
    model: 'MGB',
    specs: [
      { label: 'Engine',      value: '1.8L Inline-4 (B-Series)' },
      { label: 'Horsepower',  value: '95 hp' },
      { label: '0–60 mph',    value: '11.5 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'The MGB defined British open-top motoring for a generation. Over half a century on, it still stops people in their tracks.',
  },

  // ── May 15 ──────────────────────────────────────────────────────────────────
  {
    owner: 'yvon',
    car: '2014-porsche-911-turbo-s',
    displayName: 'Yvon',
    year: '2014',
    make: 'Porsche',
    model: '911 Turbo S Cabriolet',
    color: 'Basalt Black Metallic',
    specs: [
      { label: 'Engine',      value: '3.8L Twin-Turbo Flat-Six (991.1)' },
      { label: 'Horsepower',  value: '560 hp @ 6,500–6,750 rpm' },
      { label: 'Torque',      value: '516 lb-ft (553 lb-ft w/ Overboost)' },
      { label: 'Transmission', value: '7-Speed PDK' },
      { label: 'Top Speed',   value: '197 mph (318 km/h)' },
      { label: '0–60 mph',    value: '2.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'AWD' },
    ],
    note: '560 horsepower, open sky, and enough all-wheel-drive sophistication to make any road feel like yours. The 991 Turbo S Cabriolet is Porsche at its most complete.',
    mods: 'PCCB ceramic brakes (yellow calipers) · PDCC active anti-roll · Rear-axle steering · Active aero (front spoiler + variable rear wing) · 20" forged wheels with central locking',
  },
  {
    owner: 'daniel',
    car: '2025-porsche-cayman-gts-40',
    displayName: 'Daniel',
    year: '2025',
    make: 'Porsche',
    model: '718 Cayman GTS 4.0',
    color: 'Chalk',
    specs: [
      { label: 'Engine',      value: '4.0L Naturally Aspirated Flat-Six' },
      { label: 'Horsepower',  value: '394 hp' },
      { label: 'Transmission', value: '6-Speed Manual' },
      { label: '0–60 mph',    value: '3.8 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'Chalk, manual, ceramic brakes. Daniel configured the Cayman the way Porsche\'s own engineers would — for the driver, not the spec sheet.',
    mods: 'PCCB ceramic brakes (factory option)',
  },

  // ── May 14 ──────────────────────────────────────────────────────────────────
  {
    owner: 'aliyan',
    car: '2008-bmw-m3',
    displayName: 'Aliyan',
    year: '2008',
    make: 'BMW',
    model: 'M3 (E92)',
    specs: [
      { label: 'Engine',      value: '4.0L Naturally Aspirated V8 (S65)' },
      { label: 'Horsepower',  value: '414 hp' },
      { label: '0–60 mph',    value: '4.7 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'The S65 V8 is one of the last great naturally aspirated M engines — 8,400 rpm of pure mechanical honesty.',
  },
  {
    owner: 'thomas',
    car: '2023-dodge-challenger-rt-last-call',
    displayName: 'Thomas',
    year: '2023',
    make: 'Dodge',
    model: 'Challenger R/T Last Call',
    specs: [
      { label: 'Engine',      value: '5.7L HEMI V8' },
      { label: 'Horsepower',  value: '375 hp' },
      { label: 'Torque',      value: '410 lb-ft' },
      { label: '0–60 mph',    value: '5.7 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'The final curtain call for an American muscle car icon that ran for 16 years. Thomas drove the last of a breed to Montreal.',
  },
  {
    owner: 'lou',
    car: '2015-subaru-brz-rocket-bunny',
    displayName: 'Lou',
    year: '2015',
    make: 'Subaru',
    model: 'BRZ',
    color: 'WR Blue Pearl',
    specs: [
      { label: 'Engine',      value: '2.0L Naturally Aspirated Flat-4 (FA20)' },
      { label: 'Horsepower',  value: '200 hp' },
      { label: '0–60 mph',    value: '6.4 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'Rocket Bunny wide-body and WR Blue Pearl — the Japanese tuner dream made real on Montreal streets.',
    mods: 'Rocket Bunny wide-body kit',
  },
  {
    owner: 'patrick',
    car: '1983-fiat-spider',
    displayName: 'Patrick',
    year: '1983',
    make: 'Fiat',
    model: 'Spider 2000',
    specs: [
      { label: 'Engine',      value: '2.0L DOHC Inline-4 (Fuel Injected)' },
      { label: 'Horsepower',  value: '102 hp' },
      { label: 'Torque',      value: '110 lb-ft' },
      { label: '0–60 mph',    value: '10.1 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'Pininfarina-designed, Fiat-built, and still turning heads four decades later. The Spider 2000 is Italian open-air motoring in its most honest form.',
  },
  {
    owner: 'luc',
    car: '2018-cadillac-escalade-platinum',
    displayName: 'Luc',
    year: '2018',
    make: 'Cadillac',
    model: 'Escalade Platinum',
    specs: [
      { label: 'Engine',      value: '6.2L Naturally Aspirated V8' },
      { label: 'Horsepower',  value: '420 hp' },
      { label: '0–60 mph',    value: '6.1 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD (4WD available)' },
    ],
    note: 'Remapped, lowered, and wearing Vogue tyres — this Escalade blurs the line between luxury SUV and something far more personal.',
    mods: 'Air intake · Magnaflow exhaust · Max Track lowering kit · PFI Tuning remap · Vogue tyres',
  },
  {
    owner: 'luc',
    car: '1975-chevrolet-caprice-classic',
    displayName: 'Luc',
    year: '1975',
    make: 'Chevrolet',
    model: 'Caprice Classic',
    specs: [
      { label: 'Engine',      value: '7.4L V8 (454 cu in)' },
      { label: 'Horsepower',  value: '215 hp' },
      { label: '0–60 mph',    value: '~13 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'Air ride, wire wheels, and a 454 cubic-inch V8. The Caprice Classic is American steel from an era when big meant something.',
    mods: 'Air ride · 14" wire wheels · Custom interior · OEM swivel seats & floor shifter (Mexican market exclusive)',
  },
  {
    owner: 'xavier',
    car: '2003-porsche-boxster-s',
    displayName: 'Xavier',
    year: '2003',
    make: 'Porsche',
    model: 'Boxster S',
    color: 'Silver',
    specs: [
      { label: 'Engine',      value: '3.2L Flat-Six (Mid-Engine)' },
      { label: 'Horsepower',  value: '258 hp' },
      { label: '0–60 mph',    value: '5.5 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'The M030 Sport Chassis Package transformed the Boxster S into a driver\'s machine, not just a weekend car. Twenty years later, that distinction is even more apparent.',
    mods: 'M030 Sport Chassis Package',
  },
  {
    owner: 'jeanphilippe',
    car: '2011-bmw-135i',
    displayName: 'Jean-Philippe',
    year: '2011',
    make: 'BMW',
    model: '135i',
    specs: [
      { label: 'Engine',      value: '3.0L Twin-Turbo Inline-6 (N55)' },
      { label: 'Horsepower',  value: '300 hp' },
      { label: '0–60 mph',    value: '5.0 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'The 1 Series is BMW\'s best-kept secret. A straight-six in a compact, rear-wheel-drive shell — one of the finest combinations the brand ever put together.',
  },
  {
    owner: 'julien',
    car: '2005-porsche-911-carrera-s',
    displayName: 'Julien',
    year: '2005',
    make: 'Porsche',
    model: '911 Carrera S Cabriolet',
    specs: [
      { label: 'Engine',      value: '3.8L Flat-Six' },
      { label: 'Horsepower',  value: '355 hp' },
      { label: '0–60 mph',    value: '4.8 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'Open-air 997 motoring — 3.8 litres of flat-six behind you, the summer sky above. The Carrera S Cabriolet is the reward for getting the spec right.',
  },
  {
    owner: 'normand',
    car: 'chevrolet-corvette-c8',
    displayName: 'Normand',
    year: '2020',
    make: 'Chevrolet',
    model: 'Corvette Stingray C8',
    specs: [
      { label: 'Engine',      value: '6.2L Naturally Aspirated V8 (LT2)' },
      { label: 'Horsepower',  value: '490 hp' },
      { label: '0–60 mph',    value: '2.9 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD (mid-engine)' },
    ],
    note: 'America finally put the engine in the middle. The C8 Stingray arrived and changed the conversation about what a Corvette could be — permanently.',
  },
  {
    owner: 'paul',
    car: '2013-porsche-boxster',
    displayName: 'Paul',
    year: '2013',
    make: 'Porsche',
    model: 'Boxster',
    specs: [
      { label: 'Engine',      value: '2.7L Flat-Six (Mid-Engine)' },
      { label: 'Horsepower',  value: '265 hp' },
      { label: '0–60 mph',    value: '5.5 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'The 981 generation Boxster is widely regarded as Porsche\'s most balanced sports car — mid-engine, naturally aspirated, and built without compromise.',
  },
  {
    owner: 'thaira',
    car: '1997-bmw-z3',
    displayName: 'Thaira',
    year: '1997',
    make: 'BMW',
    model: 'Z3',
    specs: [
      { label: 'Engine',      value: '1.9L Inline-4 (M44)' },
      { label: 'Horsepower',  value: '138 hp' },
      { label: '0–60 mph',    value: '8.6 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'Introduced to the world in a Bond film. The Z3 made open-top BMW motoring accessible — and made it look completely effortless.',
  },
  {
    owner: 'yves',
    car: '2021-porsche-911-carrera-4',
    displayName: 'Yves',
    year: '2021',
    make: 'Porsche',
    model: '911 Carrera 4',
    specs: [
      { label: 'Engine',      value: '3.0L Twin-Turbo Flat-Six' },
      { label: 'Horsepower',  value: '379 hp' },
      { label: '0–60 mph',    value: '4.0 sec (stock)' },
      { label: 'Drivetrain',  value: 'AWD' },
    ],
    note: 'The 992 brought new sophistication to a formula perfected over fifty years. All-wheel drive, all-weather, all Porsche.',
  },
  {
    owner: 'domenic',
    car: '2008-corvette-z06',
    displayName: 'Domenic',
    year: '2008',
    make: 'Chevrolet',
    model: 'Corvette Z06',
    color: 'Velocity Yellow',
    specs: [
      { label: 'Engine',      value: '7.0L Naturally Aspirated V8 (LS7)' },
      { label: 'Horsepower',  value: '550 whp' },
      { label: '0–60 mph',    value: '3.7 sec (stock)' },
      { label: 'Drivetrain',  value: 'RWD' },
    ],
    note: 'The LS7 is an engine legend: 7.0 litres, naturally aspirated, 505 factory horses — now 550 at the wheels. Velocity Yellow makes sure everyone knows it\'s coming.',
    mods: 'Milled/ported heads · Kooks 2" headers · Kooks catless X-pipe · Custom mufflers',
  },
]

export function getCar(owner, car) {
  return CARS.find(c => c.owner === owner && c.car === car) || null
}

export default CARS
