// Import Cars & Coffee May 9 registrations into the applications table
// Run: node --env-file=.env.local scripts/import-cc.mjs

import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
)

const records = [
  { name: 'Thomas Khoury',          email: 'thomaskhoury@live.com',              car_year: '2014', car_model: 'Porsche 911',                               phone: '(438) 995-7187', instagram: null,              source: 'Friend / Word of mouth', more: null },
  { name: 'Daniella Abbas',          email: 'daniellaabbas99@hotmail.com',        car_year: '2013', car_model: 'Mazda 3',                                   phone: null,             instagram: null,              source: 'Friend / Word of mouth', more: null },
  { name: 'Justin Dagenais',         email: 'justin.dagenais1980@gmail.com',      car_year: null,   car_model: 'Chevrolet Belair',                           phone: '(514) 914-1970', instagram: null,              source: 'Facebook',               more: null },
  { name: 'Aleksei Trubnikov',       email: 'tralmail@gmail.com',                 car_year: '2009', car_model: 'Mazda MX-5 Miata',                          phone: null,             instagram: null,              source: 'Facebook',               more: null },
  { name: 'Mathys Chamberland',      email: 'mmathyschamberland@gmail.com',       car_year: null,   car_model: 'Photographer',                              phone: '(438) 838-0858', instagram: 'mr.mc12',         source: 'Friend / Word of mouth', more: null },
  { name: 'Erick Paulino',           email: 'paulino_24@outlook.com',             car_year: '2014', car_model: 'Mercedes Benz C300',                        phone: '(438) 372-1347', instagram: 'paulinoeprc',     source: 'Instagram',              more: 'I really like cars, my favorite brand is Mercedes Benz and I drive the car I always dreamed of; I love going on trips in my car' },
  { name: 'Gregory Krief',           email: 'gregorykrief@gmail.com',             car_year: null,   car_model: 'Dodge Charger R/T Daytona',                 phone: '(514) 574-0984', instagram: null,              source: 'Facebook',               more: null },
  { name: 'Ruben Aparicio',          email: 'rubenaparicio2016@gmail.com',        car_year: null,   car_model: 'Volkswagen Golf R MK8.5',                   phone: null,             instagram: 'Mk8larosa',       source: 'Facebook',               more: 'Meets/Ride/Car events' },
  { name: 'Aidan Tkachenko',         email: 'aidan.tkachenko1346@gmail.com',      car_year: '2015', car_model: 'Infiniti Q50 (Modified)',                   phone: '(514) 664-4634', instagram: 'slow_chenko',     source: 'Facebook',               more: null },
  { name: 'Al Buona',                email: 'albertob@videotron.ca',              car_year: '2025', car_model: 'Corvette C8 Z06',                           phone: '(514) 715-6971', instagram: null,              source: 'Facebook',               more: null },
  { name: 'Travis Lockey-Chatham',   email: 'travislockeychatham@hotmail.com',    car_year: '2026', car_model: 'Volkswagen Golf R',                         phone: null,             instagram: 'TLC94R',          source: 'Facebook',               more: null },
  { name: 'Yves Quintal',            email: 'yquintal@katera.ca',                 car_year: null,   car_model: 'Porsche Carrera 911 C4',                    phone: '(514) 591-4052', instagram: null,              source: 'Facebook',               more: null },
  { name: 'Sebastien Emond',         email: 'usomontreal@gmail.com',              car_year: '1987', car_model: 'Chevrolet Caprice',                         phone: null,             instagram: null,              source: 'Friend / Word of mouth', more: null },
  { name: 'Bobby Trippay',           email: 'johnmclane1957@gmail.com',           car_year: '1954', car_model: 'Belair Lowrider',                           phone: null,             instagram: null,              source: 'Friend / Word of mouth', more: null },
  { name: 'Aliyan Amir',             email: 'ali200102@hotmail.com',              car_year: '2008', car_model: 'BMW M3',                                    phone: '(438) 725-7005', instagram: 'aliyan1502',      source: 'Facebook',               more: null },
  { name: 'Léopold Lévesque',        email: 'leopold.levesque@outlook.com',       car_year: null,   car_model: 'BMW M Roadster',                            phone: null,             instagram: null,              source: 'Facebook',               more: 'Love classic BMWs and Porsches' },
  { name: 'Charles N',               email: 'qc.centuryv12@gmail.com',            car_year: '1997', car_model: 'Toyota Century',                            phone: null,             instagram: 'qc.century',      source: 'Instagram',              more: "I'm all about the community. A chill guy who enjoys watching clean builds and sharing the passion" },
  { name: 'Thaira Jane',             email: 'thaira_janecatembung@yahoo.com',     car_year: '1997', car_model: 'BMW Z3',                                    phone: null,             instagram: null,              source: 'Facebook',               more: 'I have been learning to work on my car each summer since I first got it, and I genuinely enjoy the process. I am passionate about sports and staying active in general, and I have a strong interest in continuous learning. At the moment, I am particularly interested in developing skills in welding and automotive painting. I also have a deep appreciation for vintage cars. My interests range widely, from quieter activities like reading to more adrenaline-driven pursuits such as skateboarding.' },
  { name: 'Domenic Agnellini',       email: 'agnellini.dom@gmail.com',            car_year: '2008', car_model: 'Corvette Z06',                              phone: null,             instagram: 'Z06.dom',         source: 'Facebook',               more: null },
  { name: 'Jimmy Lee',               email: 'montreal779@gmail.com',              car_year: '1992', car_model: 'Mercedes Benz W140 S-Class',                phone: null,             instagram: null,              source: 'Facebook',               more: null },
  { name: 'Jacques Fabrice Etoumbe', email: 'jackichigotv@gmail.com',             car_year: '2016', car_model: 'Subaru WRX',                                phone: null,             instagram: 'ja_s_pa',         source: 'Facebook',               more: 'I like animes, video games and cars, I like telling stories with my camera and more than anything drive. especially if it\'s not in the city.' },
  { name: 'Elias Jakji',             email: 'eliasjakji@gmail.com',               car_year: '2016', car_model: 'BMW 328i',                                  phone: null,             instagram: null,              source: 'Friend / Word of mouth', more: null },
  { name: 'Jean-Sébastien Hallal',   email: 'jeanhallal@gmail.com',               car_year: null,   car_model: 'Volkswagen Golf R',                         phone: null,             instagram: null,              source: 'Facebook',               more: "I'm all about driving the best routes!" },
  { name: 'Ysaac Gignac',            email: 'ysaac06@icloud.com',                 car_year: '2000', car_model: 'Subaru Legacy B4 RSK',                      phone: '(514) 833-7703', instagram: null,              source: 'Facebook',               more: 'Looking to make friends in the car community and have fun' },
  { name: 'Adam Black',              email: 'adam-mtl@outlook.com',               car_year: null,   car_model: 'BMW Z4',                                    phone: null,             instagram: null,              source: 'Facebook',               more: "I got into cars last summer, test drove about 20 and recently bought a Z4." },
  { name: 'Mikhail Shmatkov',        email: 'shmatkov.mikhaild@gmail.com',        car_year: '2014', car_model: 'Mercedes C350 Coupe',                       phone: '(514) 869-7569', instagram: null,              source: 'Facebook',               more: "Love cars and bikes, love working on them, like to see what people do and have as a car not as omg an m3 because of TikTok, but more of the story why and how a person got it whatever the car is i think it has a story to share that is very interesting. Im a detailer also so i keep my car very clean for its year and mileage" },
  { name: 'Thomas Varvier',          email: 'thomvarvier@gmail.com',              car_year: '2023', car_model: 'Dodge Challenger R/T',                      phone: null,             instagram: null,              source: 'Instagram',              more: null },
  { name: 'Théo Bégin',              email: 'theobegin2004@hotmail.com',           car_year: null,   car_model: 'Volvo XC70 Polestar Platinum',              phone: '(181) 921-5311', instagram: 'drivenbycars._',  source: 'Facebook',               more: "I love cars, modifying taking care of them, take photos of them. I got a Volvo xc70 with a 3.0L turbo inline 6 with a sport exhaust, sport suspension, a polestar tune and other tasteful mods. It's so clean I bet you 100$ you couldn't guess what's the mileage. I would love to take photos of the event while showing my one off Volvo." },
  { name: 'Lou Schirra',             email: 'schirral@gmail.com',                 car_year: '2015', car_model: 'Subaru BRZ Rocket Bunny',                   phone: '(337) 707-1090', instagram: 'louuol_sch',      source: 'Facebook',               more: null },
  { name: 'Riley Osullivan',         email: 'rileyosullivan8@gmail.com',           car_year: '2015', car_model: 'BMW F32 435i',                              phone: '(514) 885-6779', instagram: null,              source: 'Facebook',               more: null },
  { name: 'Paul Laflamme',           email: 'pflaflamme@gmail.com',               car_year: '2013', car_model: 'Porsche Boxster',                           phone: '(514) 793-4514', instagram: null,              source: 'Facebook',               more: 'I love going for casual country drives with friends or like minded people in sports cars.' },
  { name: 'Amir Ashtari',            email: 'ahashtary@gmail.com',                car_year: '2019', car_model: 'Volkswagen Jetta GLI',                      phone: null,             instagram: null,              source: 'Instagram',              more: null },
  { name: 'Marco Murano',            email: 'mmurano2002@hotmail.com',             car_year: '2019', car_model: 'Volkswagen Golf R Lapiz Blue',              phone: null,             instagram: null,              source: 'Instagram',              more: 'Work on cars for a living, love driving especially on twisty roads and love networking in the car community with other like minded people. My car has a few tasteful modifications but is also daily driven as I don\'t enjoy the idea of leaving my passion sitting in the garage.' },
  { name: 'Normand Gareau',          email: 'normandgareau@live.ca',              car_year: null,   car_model: 'Corvette C8 Stingray',                      phone: '(514) 995-7363', instagram: 'gareaunorm',      source: 'Instagram',              more: null },
  { name: 'Deepanshu',               email: 'igolu1628@gmail.com',                car_year: '2019', car_model: 'Volkswagen GTI',                            phone: null,             instagram: null,              source: 'Instagram',              more: null },
  { name: 'Karim A. Baki',           email: 'karimabdulbaki@gmail.com',           car_year: '2017', car_model: 'Subaru BRZ',                                phone: null,             instagram: 'brzc6kb',         source: 'Instagram',              more: 'Grew up around winding and mountain roads therefore got the driving bug from a young age. It also allowed me to learn quickly to respect the roads as much as the car.' },
  { name: 'David Gagnon',            email: 'david@maisonsdg.com',                car_year: null,   car_model: 'Ferrari 488 GTB',                           phone: null,             instagram: 'davidgagnon82',   source: 'Facebook',               more: null },
  { name: 'Mathys Caugant',          email: 'mathyscaugant2004@gmail.com',        car_year: null,   car_model: 'Volkswagen Golf R MK7.5',                   phone: '(514) 559-6281', instagram: 'mathys_124',      source: 'Instagram',              more: "I'm a young photographer just starting out in this field. My friend is also a photographer. We could arrive earlier to take pictures of the people arriving." },
  { name: 'Jonathan Denis',          email: 'jo--denis@hotmail.com',              car_year: '2024', car_model: 'Lotus Emira V6',                            phone: '(450) 204-7410', instagram: 'thejodenis',      source: 'Facebook',               more: "TBH I'm looking for a group that drive more than generic cars... No need for only supercars/sportcars but lets have a minimum standard. I join like to go at my local car meet and bring the Emira, but I'm kinda tired to be the only decent one. Unavailable for the 9th because of mother's day, but will join other for sure if they aren't too far" },
  { name: 'Kian Famili',             email: 'kian.famili@icloud.com',             car_year: '2019', car_model: 'Audi RS3',                                  phone: null,             instagram: 'kianfamili',      source: 'Instagram',              more: "I'm into extreme aerodynamic designs in cars and the raw sound and feel of a massive performance engines." },
  { name: 'Ali Younes',              email: 'aliyounes747@outlook.com',            car_year: '2012', car_model: 'Honda CR-V',                                phone: null,             instagram: null,              source: 'Instagram',              more: null },
  { name: 'Lucas Pittelli',          email: 'l.pit72@gmail.com',                  car_year: '2001', car_model: 'Jaguar XJR',                                phone: '(647) 778-3974', instagram: 'shitakemushroom70z', source: 'Instagram',            more: 'Fabrication & Restoration. Currently working on a 1938 Studebaker for a private collector. I\'ve acquired shop space with a hoist and would like to connect to more potential clients.' },
  { name: 'Mark David',              email: 'mark_david777@yahoo.ca',             car_year: null,   car_model: 'Spectator',                                 phone: '(514) 922-5699', instagram: 'markedavid7',     source: 'Friend / Word of mouth', more: "I'm interested in all makes and models, classic and modern. I'd also be attending as a spectator." },
  { name: 'Jean Frederic Potvin',    email: 'jf@azius.ca',                        car_year: '2025', car_model: 'Maserati GranTurismo Trofeo',               phone: '(514) 586-4110', instagram: null,              source: 'Facebook',               more: null },
  { name: 'Felipe Rojas',            email: 'fr_design@live.com',                 car_year: '2022', car_model: 'BMW M3 Competition',                        phone: '(514) 945-1905', instagram: 'frozm3',          source: 'Friend / Word of mouth', more: 'Dream GT3 RS' },
  { name: 'Jessica Li',              email: 'superdupercheeselover@gmail.com',    car_year: null,   car_model: 'Honda Civic',                               phone: '(236) 268-3155', instagram: null,              source: 'Instagram',              more: null },
  { name: 'Jean-Philippe Remon',     email: 'purp.bourassa@gmail.com',            car_year: '2011', car_model: 'BMW 135i 6MT N55 (Modified)',               phone: '(514) 226-6647', instagram: 'the_rider_13',    source: 'Friend / Word of mouth', more: 'Love the driving and seeing nice car on the road. Roads are made to be driven!' },
  { name: 'Mario Novac',             email: 'mario.novac@icloud.com',             car_year: '2026', car_model: 'BMW M4 Competition',                        phone: null,             instagram: 'f80white',        source: 'Instagram',              more: null },
  { name: 'Patrick Beauchemin',      email: 'patrickbda01@gmail.com',             car_year: '1983', car_model: 'Fiat Spider',                               phone: '(514) 581-7775', instagram: 'patrickbda',      source: 'Google',                 more: 'Car photographer & Petrolhead since... forever' },
  { name: 'Massimo Ianiro',          email: 'massino.ianiro679@gmail.com',        car_year: null,   car_model: 'Volvo XC90 (Upgraded Turbo)',               phone: null,             instagram: null,              source: 'Friend / Word of mouth', more: null },
  { name: 'Xavier Lavallee',         email: 'xavierlavallee@yahoo.ca',            car_year: '2003', car_model: 'Porsche Boxster S M030',                    phone: '(514) 880-6958', instagram: 'TheHiddenSS',     source: 'Facebook',               more: null },
  { name: 'Auston Plotkin',          email: 'aplotkin20@gmail.com',               car_year: '1972', car_model: 'Chevrolet Camaro Big Block',                phone: '(514) 821-5356', instagram: 'austomotive',     source: 'Instagram',              more: null },
  { name: 'Luc Bardier Du Temple',   email: 'lucbardierdutemple@gmail.com',       car_year: '2018', car_model: 'Cadillac Escalade Platinum / Chevrolet Caprice Classic 1975', phone: '(514) 835-5650', instagram: 'lucasbrasi', source: 'Friend / Word of mouth', more: 'Absolute car and truck fan been in the industry for 25years now' },
  { name: 'Julien Fernandez',        email: 'julien.fernandez.911@gmail.com',     car_year: null,   car_model: 'Porsche 997 S',                             phone: '(514) 581-3401', instagram: '6Flat.ca',        source: 'Instagram',              more: null },
  { name: 'Baz Burgess',             email: 'discobaz2003@yahoo.com',             car_year: null,   car_model: null,                                        phone: '4506926625',     instagram: null,              source: 'Facebook',               more: null },
  { name: 'Louis Guindon',           email: 'louisguindon@hotmail.com',           car_year: '2023', car_model: 'Genesis G70 3.3',                           phone: '(514) 704-4565', instagram: null,              source: 'Instagram',              more: 'Dream routes in Portugal' },
  { name: 'James Blakely',           email: 'blakely.jameswilliam@gmail.com',     car_year: '2001', car_model: 'Mazda Miata',                               phone: '(438) 921-7393', instagram: null,              source: 'Facebook',               more: "I'm just here for the classic car chitchat, the people, the coffee, the food, and the occasional Mezger disturbing the peace. I'm spreading my passion with my kids now and they love it. I like the twisty bits just as much as everyone else, but we need some Saad Tekiouts out in full force before I blow up my 205 section tire." },
  { name: 'Vlad',                    email: 'calivlad02@gmail.com',               car_year: '1983', car_model: 'BMW 520i Euro 5-Speed',                     phone: null,             instagram: null,              source: 'Instagram',              more: null },
  { name: 'Othmane Zenati',          email: 'o.zenati@hotmail.com',               car_year: '2026', car_model: 'BMW M4',                                    phone: '(514) 250-1573', instagram: 'LOBZ_G82',        source: 'Instagram',              more: null },
  { name: 'Jordan Wohlmuth',         email: 'jordan.wohlmuth@gmail.com',          car_year: null,   car_model: 'Spectator',                                 phone: null,             instagram: null,              source: 'Facebook',               more: null },
  { name: 'Ben Omar',                email: 'oben1787@gmail.com',                 car_year: null,   car_model: 'Mercedes CLA',                              phone: null,             instagram: '1darkcla',        source: 'Instagram',              more: null },
  { name: 'Ali Bensaid',             email: 'bensaidali35@gmail.com',             car_year: '2019', car_model: 'BMW M550i',                                 phone: null,             instagram: 'Prahnaa',         source: 'Friend / Word of mouth', more: null },
  { name: 'Loran Arkhame',           email: 'loran@arkhame.com',                  car_year: '2018', car_model: 'AMG GTC Roadster / Mercedes AMG E53 Cabriolet / AMG GLE53 / BMW M4 Compétition', phone: null, instagram: null, source: 'Facebook', more: null },
  { name: 'Samy Benkacimi',          email: 'samybenkacimi@hotmail.com',          car_year: '2022', car_model: 'BMW M3 Competition',                        phone: null,             instagram: 'woolg80',         source: 'Instagram',              more: null },
  { name: 'George Jacobs',           email: 'george@federalmufflers.ca',          car_year: '1969', car_model: 'Chevrolet Camaro SS',                       phone: '(514) 999-9252', instagram: null,              source: 'Facebook',               more: null },
  { name: 'Rodrigo Perez',           email: 'rodrigoqaz12@gmail.com',             car_year: null,   car_model: 'BMW 328i',                                  phone: '(438) 229-9502', instagram: 'perez.rodrigo',   source: 'Facebook',               more: null },
  { name: 'David M.',                email: 'triple.seven787@outlook.com',        car_year: '2019', car_model: 'Mercedes C43 AMG Coupe',                    phone: null,             instagram: null,              source: 'Facebook',               more: null },
  { name: 'Momo Elrefai',            email: 'momo_elrefai@hotmail.com',           car_year: null,   car_model: 'RAM TRX',                                   phone: '(514) 791-1829', instagram: null,              source: 'Facebook',               more: null },
]

async function run() {
  console.log(`Importing ${records.length} records…`)

  const rows = records.map(r => ({
    ...r,
    email: r.email.toLowerCase().trim(),
  }))

  const { error, data } = await supabase
    .from('applications')
    .upsert(rows, { onConflict: 'email' })
    .select('email')

  if (error) {
    console.error('Error:', error.message)
    process.exit(1)
  }

  console.log(`Done — ${data.length} records inserted/updated.`)
  data.forEach(r => console.log(' ✓', r.email))
}

run()
